{% set name = "saspy" %}
{% set version = "2.2.8" %}
{% set hash_type = "sha256" %}
{% set hash_val = "a9ef5c7e7ea0b939675076129863f4d03a40f97f3faa00185f016cd79acaaf80" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python >=3
    - setuptools
    - pip
  run:
    - python >=3
    - ipython >=4
    - pygments
    - pandas

test:
  imports:
    - saspy

about:
  home: https://github.com/sassoftware/saspy
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A Python interface module to the SAS System

extra:
  recipe-maintainers:
    - danielfrg
