{% set name = "saspy" %}
{% set version = "3.6.5" %}
{% set hash_val = "a709819a5e8adf32534b4648ef8629e6a97aa9c93f0e4c68ed9130fec637e41b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - setuptools
    - pip
  run:
    - python >=3
    - ipython >=4
    - pygments
    - pandas

test:
  imports:
    - saspy

about:
  home: https://github.com/sassoftware/saspy
  license: Apache 2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A Python interface module to the SAS System

extra:
  recipe-maintainers:
    - danielfrg
