{% set name = "saspy" %}
{% set version = "2.2.7" %}
{% set hash_type = "sha256" %}
{% set hash_val = "ac26c5820cf8f8554e1ae7fcdd634988a25c0495ae6642efdb169c06e4d929e4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [not linux]
  skip: true  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - ipython >=4
    - pygments

test:
  imports:
    - saspy

about:
  home: https://github.com/sassoftware/saspy
  license: Apache 2.0
  summary: A Python interface module to the SAS System

extra:
  recipe-maintainers:
    - danielfrg
