{%set name = "saspy" %}
{% set version = "2.2.5" %}
{%set hash_type = "sha256" %}
{% set hash_val = "350310ca69f093cfc327470fe387cc6b1228a14e2f9be8382e98411dbc7d1a3c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [not linux]
  skip: true  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ipython >=4
    - pygments

test:
  imports:
    - saspy

about:
  home: https://github.com/sassoftware/saspy
  license: Apache 2.0
  summary: A Python interface module to the SAS System

extra:
  recipe-maintainers:
    - danielfrg
