# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MKTqp6b/L+txriuJ1VPM6l3ZaDSeVHPfs9Dyn49lCQFXxSv4igaw8hTMdyPqua+hdQkHYuxCRViSEr8xCakLh9zSAEfMCmUkCu2nek2Nn9UvzdvZMQYliVB1luEXyXkMK8ZP5twlt0gSBjbsQxyjteeq+SwXa5F8UFYp0fZJ/VGVSSAWzUT/AZWnvrWdLKAA8JtgPwLfhyH9hiQXfsb69V5X6JMp8NbJzqfz1n9joVSPmNPi+eajCGZb9QzYCYlHaZy4n9v8LSOm/vvyUTMfCqcR2MIC4ZJ03sMGJ6ip7kT7p9gu0HHq7+CA0vf+ot+YfvwJGS1jbNc4WBubfv0D/2oAnlJpEK1mbZFKLwE6G47GpZn6JlGEpWDkLVDb71x7F1ubyttVLI4IOhV7usF0VaO3TEz1SW7l7FKhfBfvNDAv+gvNFZ/G0crDlRiwvwfdBIBSpHmQR0eYyPec/lpZ1sHqjID1IKMB3JzGCbO3yl5FEU618pg9AJz4NcbH4IznyEvSLuByLAorlAavzD1vvjPXSD0eM9emW4TG8T7AgwLWys5842EmaFbgMTgO5NP04sPPO3PMWM1AyoKVQI/oGxmFdcyOc+SeZ0cfnBAN9jTz8yJY2gRG8d3KEDj7jtx56NZglAqZYFSZjcCuPjZL4DaQnLZwstSdMOJgB4TyDw4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
